day 09: run the intcode program
There's still a

    thread 'main' panicked at 'Invalid destination parameter mode 2 at ip 25', intcode\src\lib.rs:208:14

so I think I still need to work on the `intcode` crate...