day 12: implement main loop on file input
This does not compile because I need to borrow an element of the Vec as
mutable at the same time as I borrow another element of the Vec.  The
borrowchecker correctly gets angry about that:

	error[E0502]: cannot borrow `moons` as immutable because it is also borrowed as mutable
	  --> day_12\src\main.rs:75:37
	   |
	75 |             moons[i].apply_gravity(&moons[j]);
	   |             -----    -------------  ^^^^^ immutable borrow occurs here
	   |             |        |
	   |             |        mutable borrow later used by call
	   |             mutable borrow occurs here